version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3.8.0
    container_name: jekyll
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/jekyll
